name: Build and Upload Virglrenderer

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          meson \
          ninja-build \
          libegl1-mesa-dev \
          libgbm-dev \
          libdrm-dev \
          x11proto-gl-dev \
          libwayland-dev \
          wayland-protocols \
          pkg-config \
          python3-pip \
          python3-setuptools
        pip3 install mako

    - name: Create build directory
      run: mkdir build

    - name: Configure the build with Meson
      run: |
        meson setup build \
          -Dvenus-experimental=true \
          -Dplatforms=egl

    - name: Build Virglrenderer
      run: ninja -C build

    - name: Test the build
      run: ninja -C build test

    - name: Package build artifacts
      run: |
        mkdir -p output
        cp build/src/*.so output/ # Adjust the path based on the compiled files
        cp build/src/*.a output/  # Include any static libraries, if applicable
        cp build/* output/        # Optionally include everything from the build folder
      # Ensures output folder is ready for upload

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: virglrenderer-build
        path: output/
